Position caret at end after uiEntrySetText() on Windows, replicating …
libui-ng/libui-ng pull request #102
Opened 2022-06-03 16:20 UTC by adamierymenko

…behavior on MacOS

Just that. A few lines.

2022-06-04 01:58 UTC, cody271 requested changes
Same failure in CI due to odd formatting/encoding with this PR as well:
```
../windows/entry.cpp: In function 'void uiEntrySetText(uiEntry*, const char*)':
../windows/entry.cpp:69:5: error: '\U000000a0' was not declared in this scope
   69 |         int l = (int)strlen(text);
      |     ^
../windows/entry.cpp:70:2: error: expected ';' before '\U000000a0'
   70 |         if (l >= 0) {
      |  ^~
      |  ;
```

2022-06-06 04:40 UTC, szanni requested changes

2022-06-06 04:40 UTC, szanni commented on windows/entry.cpp
> +        if (l >= 0) {
Unless I am missing something: how would this condition ever be `false`? `strlen` returns `size_t`, so it is by definition always `>=0`.
I would generally prefer matching types too `size_t len = strlen(text);` and then use that.

2022-06-06 04:48 UTC, szanni commented on windows/entry.cpp
> +        if (l >= 0) {
Oh and variable declaration at the top of the function. To stay consistent,

2022-06-06 14:57 UTC, adamierymenko commented
Fixed but didn't make it size_t because I think Windows expects int.

2022-06-07 00:09 UTC, szanni requested changes

2022-06-07 00:09 UTC, szanni commented on windows/entry.cpp
> +        l = (int)strlen(text);
Indentation is one tab, not spaces. You can see the mismatch in the Github diff.

2022-06-07 00:13 UTC, szanni commented
> Fixed but didn't make it size_t because I think Windows expects int.

Yeah, well windows actually expects a signed and unsigned type. Great. `UINT_PTR` and `LONG_PTR` according to `WPARAM` and `LPARAM` as defined [here](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types).
I guess `int` is fine. It somehow does not seem to matter.

Otherwise the code does what it is supposed to. Unix behavior is matching too,

2022-06-08 02:02 UTC, szanni requested changes

2022-06-08 02:02 UTC, szanni commented on windows/entry.cpp
> +        uiWindowsSetWindowText(e->hwnd, text);
I am not sure what editor you are using, but it seems incapable of getting the indentation right?

2022-06-08 14:25 UTC, adamierymenko commented on windows/entry.cpp
> +        uiWindowsSetWindowText(e->hwnd, text);
I was using the GitHub online web editor to make small PRs. Will probably ditch that and actually check out a fork and do it in a proper editor. I guess the online editor is broken and for some reason inserts pseudo-whitespace unicode.

2022-06-08 20:50 UTC, szanni commented on windows/entry.cpp
> +        uiWindowsSetWindowText(e->hwnd, text);
Oh wow. That sucks. Seems to work here (Firefox 101 on Linux).

2022-06-18 03:23 UTC, szanni requested changes
Yup, good. The white space/indentation issues are still there though. L69-73.

2022-06-23 05:16 UTC, cody271 approved these changes
Confirmed to be passing CI.. hopefully no more GitHub online editor formatting weirdness. 😕 

I will just fix manually in master after merge. LGTM.

2022-06-23 05:16 UTC, merged

2023-10-07 18:42 UTC, szanni commented
Sorry for opening this issue again: @adamierymenko what was your exact use case here or the problematic behavior?

Is my understanding correct that this was about the caret placement when the `uiEntry` already has focus? To place the caret at the end when focused?

Because if the `uiEntry` does not have the focus the caret is always placed where I click. Correct?

Thanks

Related to #232 and #233