Possibly fix multiline labels on windows
libui-ng/libui-ng pull request #112
Opened 2022-06-18 04:35 UTC by mohad12211

unix and darwin appear to have no problems with multiline labels (would like confirm that).
this is an attempt to solve that on windows and address #106. 
the first commit from https://github.com/andlabs/libui/pull/465 to calculate the correct width and solve #106
<details>
<summary>Screenshot and code example</summary>

```c
#include <stdlib.h>
#include <string.h>
#include "../../ui.h"

int onClosing(uiWindow *w, void *data)
{
	uiQuit();
	return 1;
}

int main(int argc, char *argv[])
{
	uiInitOptions o;
	memset(&o, 0, sizeof (uiInitOptions));
	if (uiInit(&o) != NULL)
		abort();
	uiWindow *w = uiNewWindow("Hello", 100, 500, 1);
	uiBox *hbox = uiNewHorizontalBox();
	uiWindowSetChild(w, uiControl(hbox));
	uiButton *b = uiNewButton("TEST");
	uiLabel *l = uiNewLabel("1\n\n\n\n\n1\n\n\n\n\n1\n\n\n\n\n1\n\n\n\n\n1\n\n\n\n\n1\n\n\n\n\n1");
	uiBoxAppend(hbox, uiControl(b), 1);
	uiBoxAppend(hbox, uiControl(l), 1);
	uiWindowOnClosing(w, onClosing, NULL);
	uiControlShow(uiControl(w));
	uiMain();
	return 0;
}
```

before (smallest window width):
![image](https://user-images.githubusercontent.com/51754973/174422526-5969173e-905a-4844-8b51-25b6b0670bb5.png)
after: 
![image](https://user-images.githubusercontent.com/51754973/174422604-82f0b7b9-f984-4bcd-ba8e-e63d84a99e5b.png)

</details>

second commit is to calculate the correct height based on how many lines will be in the label.

<details>

<summary>Screenshot and code example</summary>

if we change the label in controlgallery to:
```c
uiControl(uiNewLabel("This is a label.\nRight now,\nlabels can\nonly span\none line.")),
```
before change:
![image](https://user-images.githubusercontent.com/51754973/174422857-cc4e4141-25a0-49db-b23c-3bbd31c689a5.png)

after change:
![image](https://user-images.githubusercontent.com/51754973/174422838-f83acd84-0582-4dad-8ea4-c42e3c9b0748.png)

</details>

2022-06-24 02:35 UTC, cody271 reviewed
This is comparing an ASCII literal against UTF-16 strings to parse the newlines. Otherwise looks good.

2022-06-24 02:35 UTC, cody271 commented on windows/text.cpp
> +		if (*start == '\n')
```suggestion
		if (*start == L'\n')
```

2022-06-24 02:35 UTC, cody271 commented on windows/text.cpp
> +		while(*start == '\n' && start != text + len) {
```suggestion
		while(*start == L'\n' && start != text + len) {
```

2022-06-24 02:35 UTC, cody271 commented on windows/text.cpp
> +		while(*end != '\n' && end != text + len){
```suggestion
		while(*end != L'\n' && end != text + len){
```

2022-06-24 02:37 UTC, cody271 commented
> unix and darwin appear to have no problems with multiline labels (would like confirm that).

Confirmed to be a Windows only issue, correct.

> Screenshot and code example

This always makes reviewing much easier, thanks! 👍 

Maybe now also update that label text in the `controlgallery` example to reflect the fact that we _do_ support multiline labels on all platforms? ;)

> This only addresses `uiLabel`, what about `uiForm`? does it make sense to have a form with multiline label?

I wouldn't worry about supporting multiline labels in forms, no.

2022-06-30 16:45 UTC, szanni requested changes
Nice work, definitely seems to work according to my tests.

Apart from removing out the old, now unneeded cruft, please remove the curly braces around the single if statements. The general guideline is to add them only when nesting gets too crazy or to match `if/else` blocks.

And please add the missing spaces around `if ()` and `while ()` statements. You did it in some places but not others.

Edit: and all the things @cody271 suggested of course.

2022-06-30 16:45 UTC, szanni commented on windows/text.cpp
> +	WCHAR *start = text, *end = text;
Variable declaration always at the top.
And I would move the assignment just before the while loop, not somewhere in the middle of other code like so.
Assignment IMO looks nicer like this too: `start = end = text;`

2022-06-30 16:45 UTC, szanni commented on windows/text.cpp
> +	auto maxWidth = size.cx;
```suggestion
	int maxWidth = 0;
```

2022-06-30 16:45 UTC, szanni commented on windows/text.cpp
>  	size.cy = 0;
```suggestion
```
Not needed anymore.

2022-06-30 16:45 UTC, szanni commented on windows/text.cpp
> +		}
```suggestion
		if (GetTextExtentPoint32W(dc, start, end - start, &size) == 0)
			logLastError(L"error getting text extent point");
		else
			if (size.cx > maxWidth)
				maxWidth = size.cx;
```
Looks clearer to me and removes a bunch of lines this way.

2022-07-02 00:41 UTC, szanni requested changes
Missed the memory leak in my first review.

2022-07-02 00:41 UTC, szanni commented on windows/text.cpp
> +
```suggestion
	uiprivFree(text);
```
Leaking memory here.

2022-07-14 03:11 UTC, szanni approved these changes
Very nice. Code looks good to me.

I tested things as well under Window 7 with assistive technologies, as I was a little concerned about the hard coded line height. Results:

100% font/icon size:
![small](https://user-images.githubusercontent.com/286606/178889563-9b3da6f3-dbe8-46b1-a243-6f0d8dd10c30.png)

150% font/icon size:
![big](https://user-images.githubusercontent.com/286606/178889604-fa4252c3-22a7-4e75-a141-57b6d68d6a66.png)

It seems like Windows actually takes care of things via some type of smart scaling. So all good it seems.

2022-07-18 01:39 UTC, merged