Rename static library suffix for Windows MSVC
libui-ng/libui-ng pull request #291
Opened 2024-08-08 01:19 UTC by kojix2

Change the static library extension to .lib for MSVC.

See #290

2024-08-12 22:44 UTC, petabyt commented
LGTM @cody271

2024-09-18 15:30 UTC, matyalatte commented on meson.build
> +
You can use `[]` for the default behavior.
```suggestion
libui_suffix = []
if libui_OS == 'windows' and libui_MSVC
	libui_suffix = 'lib'
endif

```

2024-12-15 06:15 UTC, cody271 requested changes
This doesn't work? Builds immediately fail with:
```
meson.build:170:41: ERROR: Unknown variable "static_lib_suffix".
```

2025-05-27 04:32 UTC, kojix2 commented
There are many other issues that may be more important.

2025-05-27 04:32 UTC, closed without merging