New examples
libui-ng/libui-ng pull request #34
Opened 2022-01-16 17:30 UTC by inkydragon

- `hello-world`: Display a window. Using as few statements as possible may not be the best practice.
- `hello-window`: Display a window and add a label to the window, using best practices where possible.

TODO: Add more standalone `hello-widgets` examples.

2022-01-17 00:59 UTC, cody271 commented
Aren't these two new examples the same?

2022-01-17 01:05 UTC, cody271 commented
> Aren't these two new examples the same?
>
(Nevermind. I see one creates a label in the window.)

Maybe the examples should be something like `hello-window-1.c` and `hello-label-2.c`, to make it clear they are part of a series of examples?

2022-01-17 03:20 UTC, cody271 commented
Also we could add `doc/examples.md` to link all the examples together from the Doxygen main page, including some screenshots of each example with the code.

2022-01-17 05:19 UTC, inkydragon commented
> Maybe the examples should be something like hello-window-1.c and hello-label-2.c, to make it clear they are part of a series of examples?

Yes! For some simple examples, a single c file may be enough, no need to create a separate folder.

My proposal:
- `screenshots/`: All in one directory for centralized referencing.
- `widgets/`
  - hello-label.c
  - `hello-window/`
    - hello-window-1.c
    - hello-window-2.c
  - `hello-xxx/`
  - hello-xxx.c

----

> including some screenshots of each example with the code.

We would write a simple example for each widget, so that there would be a lot of images.

Should we put all the images in the library here?

If it's hard to decide in a short time. 
We can set an upper size limit for all images, for example: 10 MB, and wait until all images are over the limit, then split them into separate libraries.

2022-01-17 06:20 UTC, cody271 commented
> 
> Yes! For some simple examples, a single c file may be enough, no need to create a separate folder.
> 
Yup single C file per example is totally fine. We should put the whole example series under maybe `examples/tutorial`, something that's easy to find. Then GitHub will automatically load `examples/tutorial/README.md`.

>
> Should we put all the images in the library here?
> 
> If it's hard to decide in a short time. We can set an upper size limit for all images, for example: 10 MB, and wait until all images are over the limit, then split them into separate libraries.
>
I think its okay for now, we can move it later if they are too big. 10MB is probably a good limit. We already have 188KB of images for one example.
```sh
libui-ng$ du -hc examples/controlgallery/*.png
 96K	examples/controlgallery/darwin.png
 44K	examples/controlgallery/unix.png
 48K	examples/controlgallery/windows.png
188K	total
```

2022-01-17 15:02 UTC, szanni commented
> Maybe the examples should be something like `hello-window-1.c` and `hello-label-2.c`, to make it clear they are part of a series of examples?

I would definitely put label in the file name. Makes it much clearer and more discoverable.

Apart from that: if we should add more screenshots I believe we should optimize them before submitting them upstream.
I was able to reduce the size of the existing screenshots by ~25% by running them through `optipng -o7` and `zopflipng -m`. Just so we bloat the repo as little as possible.

```
% du -hc examples/controlgallery/*.png                                                                                                                                                                                                
65K	examples/controlgallery/darwin.png
37K	examples/controlgallery/unix.png
41K	examples/controlgallery/windows.png
142K	total
```

2022-01-18 05:49 UTC, cody271 commented
> 
> I believe we should optimize them before submitting them upstream.
> Just so we bloat the repo as little as possible.
> 
Absolutely. 💯 

Repo needs to remain small enough to clone quickly!

2022-06-24 18:55 UTC, szanni requested changes
Apart from the small suggestions and missing `uiUninit`, I would rename the files.
`hello-world` should print "Hello World!" in the window. As a user I would expect the two files to contain the exact opposite.
`hello-window`: creates a window
`hello-world`: creates a window printing hello world

Otherwise the other naming suggestions would be fine too I guess. But I probably would remove the _hello_ in that case. Just name them `window`, `label`, etc. And the current `hello-window` as a `hello-world`, just because of the custom.

2022-06-24 18:55 UTC, szanni commented on examples/hello-window/main.c
> +    uiQuit();
Indentation throughout the project is 1 tab. I believe this should be enforced in the examples as well.

2022-06-24 18:55 UTC, szanni commented on examples/hello-world/main.c
> +    return 0;
Missing 
```suggestion
    uiUninit();
    return 0;
```

2022-06-24 18:55 UTC, szanni commented on examples/hello-world/main.c
> +    if (uiInit(&o) != NULL) exit(1);
Do we want to make error handling consistent across examples? Why not error printing here?

2022-06-25 13:23 UTC, inkydragon commented on examples/hello-world/main.c
> +    if (uiInit(&o) != NULL) exit(1);
I just want to keep this example as simple as possible.

> make error handling consistent across examples

This is a good point. So I'll add error handling.

2022-06-28 18:27 UTC, szanni requested changes
Very nice. I believe we can remove the two includes. And I would still swap the two file names. I am greeted with an empty window on my system when running hello world. I do not see the text `hello world` which is the custom.

2022-06-28 18:27 UTC, szanni commented on examples/hello-world/main.c
> +#include <stdlib.h> // exit
Can be removed as there is not call to exit() anymore.

2022-06-28 18:27 UTC, szanni commented on examples/window/main.c
> +#include <stdlib.h> // exit
Can be removed as there is not call to exit() anymore.

2022-08-11 23:25 UTC, mohad12211 commented
Now that we have good documentation, unit testing, a11y and [QA](https://github.com/libui-ng/libui-ng/pull/133) soon, what's missing are new simple examples for most controls with screenshots, because the current `controlgallery` and `histogram` don't appear welcoming for newcomers at all. 

> Maybe the examples should be something like hello-window-1.c and hello-label-2.c, to make it clear they are part of a series of examples?

This looks good.

>  And I would still swap the two file names

yes, I think `hello-window` should show a window, `hello-world` should show hello world, inside a label.

2022-12-03 08:23 UTC, szanni requested changes
Switch the file names around. Not all systems display window titles. The `hello-world` program just displays an empty window for me.

2022-12-03 08:23 UTC, szanni commented on examples/hello-world/main.c
> +#include <string.h> // memset
```suggestion
```

2022-12-03 08:23 UTC, szanni commented on examples/hello-world/main.c
> +#include <stdlib.h> // exit
```suggestion
```

2022-12-03 08:23 UTC, szanni commented on examples/hello-world/main.c
> +#include "../../ui.h"
```suggestion
#include <ui.h>
```

So this can virtually be dropped into place.
We might need to tell meson to add the top level directory to the include path? Not sure, but this may already be the case.

2022-12-03 08:23 UTC, szanni commented on examples/hello-world/main.c
> +	uiInitOptions o;
```suggestion
	uiInitOptions o = {0};
```

2022-12-03 08:23 UTC, szanni commented on examples/hello-world/main.c
> +	memset(&o, 0, sizeof (uiInitOptions));
```suggestion
```

2022-12-03 08:23 UTC, szanni commented on examples/window/main.c
> +#include <string.h> // memset
```suggestion
```

2022-12-03 08:23 UTC, szanni commented on examples/window/main.c
> +#include "../../ui.h"
```suggestion
#include <ui.h>
```

2022-12-03 08:23 UTC, szanni commented on examples/window/main.c
> +	uiInitOptions o;
```suggestion
	uiInitOptions o = {0};
```

2022-12-03 08:23 UTC, szanni commented on examples/window/main.c
> +	memset(&o, 0, sizeof (uiInitOptions));
```suggestion
```

2022-12-04 06:05 UTC, closed without merging