uiSliderOnReleased API
libui-ng/libui-ng pull request #91
Opened 2022-05-14 06:06 UTC by MikeWang000000

windows implementation added.
issue #89

2022-05-14 08:18 UTC, cody271 requested changes

2022-05-14 08:18 UTC, cody271 commented on unix/slider.c
> +  void *onReleasedData;
```suggestion
  	void *onReleasedData;
```

2022-05-14 08:18 UTC, cody271 commented on darwin/slider.m
> +	void (*onReleased)(uiSlider *, void*);
```suggestion
	void (*onReleased)(uiSlider *, void *);
```

2022-05-14 08:18 UTC, cody271 commented on test/page4.c
> +	printf("on Slider released \n");
This callback should provide feedback within the tester GUI, instead of printing to the console.
(Just like `onRangeSliderChanged()` does above it.)

2022-05-14 08:20 UTC, cody271 commented
Resolves #89

Duplicate of #90

2022-05-14 10:32 UTC, MikeWang000000 commented
the tester uses a macro `CHANGED(what)` however it cannot be applied to slider released events.
I added a progressbar to show it.

2022-05-19 15:48 UTC, cody271 reviewed
Nit: There are two small formatting errors still, in `unix/slider.c` and `windows/slider.c`:

```shell
$ git apply 91.patch 
91.patch:193: trailing whitespace.
	
91.patch:250: space before tab in indent.
  	void *onReleasedData;
warning: 2 lines add whitespace errors.
```
Which strangely don't show up in the GitHub web UI, only in `git diff` directly..

Otherwise looks good, new `page4.c` progress bar is working for me. 👍

2022-05-20 00:47 UTC, cody271 approved these changes
LGTM

2022-05-20 00:49 UTC, merged