[All Platforms] uiWindow: add events onGetFocus / onLoseFocus
libui-ng/libui-ng pull request #93
Opened 2022-05-17 18:34 UTC by mohad12211

Tested on mac and linux. Windows is still untested.
completes #52 
what do you think about the names GetFocus and LoseFocus? andlabs said [here](https://github.com/andlabs/libui/pull/378#issuecomment-411694239): 
> Not too happy with the names GetFocus/LoseFocus, as those names tend to refer to keyboard focus, not becoming the active window

should be change them?

2022-05-19 15:58 UTC, cody271 commented
> should we change them?

I'm okay with the names `uiWindowOnGetFocus()` / `uiWindowOnLoseFocus()` as is here.

Anything related to keyboard focus could be prefixed with `Key` in the name for added clarity.

2022-05-19 16:03 UTC, cody271 commented on test/page5.c
> +	uiCheckbox *check;
The API is a read only event: you can't change the window focus programmatically.

Probably should be a label instead of a checkbox?

2022-05-20 01:39 UTC, szanni commented
> > Not too happy with the names GetFocus/LoseFocus, as those names tend to refer to keyboard focus, not becoming the active window

The typical ui convention would most likely be something like:
```c
void uiWindowOnFocusChanged(uiWindow *w, void (*f)(uiWindow *, void *), void *data);
int uiWindowFocused(uiWindow *w);
```
Or something like `uiWindowHasFocus`. The important part being one function signaling a change, and another function to be called by the user to determine the state. This way the state can be queried independently of any change.

2022-05-20 01:59 UTC, cody271 requested changes
Needs to handle both the change event and querying the state:
```c
void uiWindowOnFocusChanged(uiWindow *w, void (*f)(uiWindow *, void *), void *data);
int uiWindowFocused(uiWindow *w);
```

2022-05-23 00:48 UTC, cody271 approved these changes
Page5 test is confirmed working. LGTM.

2022-05-23 00:48 UTC, merged